### ISSUE TITLE
Fleet on non ZTF data

### ISSUE THREAD

**Issue by LydiaMak** [gmzsebastian/FLEET#6]
Hi,

Is it possible to use FLEET on local data? Lightcurve from real or simulated data?

And another question: are the results saved in any output apart from the PDF with the plot and the results for each classifier?

Cheers,
Lydia

**Comment by gmzsebastian** [comment]
Hello Lydia

The code will run, but it's not recommend since it's not validated for non-ZTF photometry.

Yes, the `predict_SLSN` function will return all necessary parameters. You can see the **Example** section on the README.
